//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UisApp.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UriResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UriResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UisApp.API.Resources.UriResource", typeof(UriResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lecturer/login.
        /// </summary>
        internal static string auth {
            get {
                return ResourceManager.GetString("auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /schedule/concrete.
        /// </summary>
        internal static string concrete_schedule {
            get {
                return ResourceManager.GetString("concrete_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /attendance/create_entries.
        /// </summary>
        internal static string create_attendance_entries {
            get {
                return ResourceManager.GetString("create_attendance_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /rating/create_entries.
        /// </summary>
        internal static string create_rating_entries {
            get {
                return ResourceManager.GetString("create_rating_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lecturer/getme.
        /// </summary>
        internal static string getme {
            get {
                return ResourceManager.GetString("getme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /schedule/lecturer.
        /// </summary>
        internal static string lecturer_schedule {
            get {
                return ResourceManager.GetString("lecturer_schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lecturer/subjects.
        /// </summary>
        internal static string lecturer_subjects {
            get {
                return ResourceManager.GetString("lecturer_subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lecturer/logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /attendance/students.
        /// </summary>
        internal static string student_attendance {
            get {
                return ResourceManager.GetString("student_attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /attendance/change_state.
        /// </summary>
        internal static string student_check {
            get {
                return ResourceManager.GetString("student_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /rating/student_rate.
        /// </summary>
        internal static string student_rate {
            get {
                return ResourceManager.GetString("student_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /rating/students.
        /// </summary>
        internal static string student_rating {
            get {
                return ResourceManager.GetString("student_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /subject/groups.
        /// </summary>
        internal static string subject_groups {
            get {
                return ResourceManager.GetString("subject_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /lecturer/update_photo.
        /// </summary>
        internal static string update_photo {
            get {
                return ResourceManager.GetString("update_photo", resourceCulture);
            }
        }
    }
}
